"""Generate the 50 single-GPU sbatch files (one per OGBench task) under sbatch/jobs/.

Each job asks for 1 A100 + 4h (the cluster's hard walltime cap), runs its task's
3 seeds sequentially via sbatch/run_task.sh, and requeues itself until every
seed's final checkpoint exists (progress state = checkpoints in exp/, nothing else).
The repo path is baked in at generation time, so regenerate after moving the repo
or editing the template:  python sbatch/gen_jobs.py
"""
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAX_WINDOWS = 18  # runaway cap: 18 x ~4h = 72 GPU-h per task (3 seeds)

# Variant knobs (baked into the generated files so requeues can't drift):
#   JOB_PREFIX=dql112 AGENT=agents/dql_v11_2.py GROUP_PREFIX=DQL112-50 python sbatch/gen_jobs.py
JOB_PREFIX = os.environ.get("JOB_PREFIX", "dql111")
AGENT = os.environ.get("AGENT", "agents/dql_v11_1.py")
GROUP_PREFIX = os.environ.get("GROUP_PREFIX", "DQL111-50")

TEMPLATE = """#!/bin/bash
#SBATCH --account=edgeai_tao-ptm_image-foundation-model-clip
#SBATCH --partition=polar4,polar3,polar,grizzly
# (batch_block1-3 excluded: this account is rejected there, which holds the whole job in PartitionConfig)
#SBATCH --time=4:00:00
#SBATCH --nodes=1
#SBATCH --gpus-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=100G
#SBATCH --dependency=singleton
#SBATCH --job-name={job}
#SBATCH --output={repo}/logs/%x.%j.log
#SBATCH --error={repo}/logs/%x.%j.log
#SBATCH --open-mode=append
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=chrislin@nvidia.com
# task {idx}: {env}
# GENERATED by sbatch/gen_jobs.py -- edit the template there, not this file.

export REPO={repo}
export AGENT={agent} GROUP_PREFIX={gprefix} RUN_PREFIX={prefix}
bash "$REPO/sbatch/run_task.sh" {idx}
rc=$?

# Requeue until run_task.sh reports the task done (rc 0), with a runaway cap.
CNT="$REPO/logs/$SLURM_JOB_NAME.windows"
n=$(($(cat "$CNT" 2>/dev/null || echo 0) + 1)); echo "$n" > "$CNT"
if [ "$rc" -eq 99 ] && [ "$n" -lt {max_windows} ]; then
    echo "[job] window $n finished with work remaining -> requeue"
    scontrol requeue "$SLURM_JOB_ID"
elif [ "$rc" -eq 99 ]; then
    echo "[job] hit MAX_WINDOWS={max_windows} with work remaining -- NOT requeueing" >&2
    exit 1
else
    exit "$rc"
fi
"""

with open(os.path.join(REPO, "slurm/tasks.tsv")) as f:
    rows = [line.rstrip("\n").split("\t") for line in f][1:]

outdir = os.path.join(REPO, "sbatch/jobs")
os.makedirs(outdir, exist_ok=True)
for idx, (env, *_hypers) in enumerate(rows):
    short = env.replace("-singletask", "").replace("-v0", "")
    job = f"{JOB_PREFIX}-t{idx:02d}-{short}"
    path = os.path.join(outdir, f"t{idx:02d}-{short}.sbatch")
    with open(path, "w") as f:
        f.write(TEMPLATE.format(repo=REPO, idx=idx, env=env, job=job, max_windows=MAX_WINDOWS,
                                agent=AGENT, gprefix=GROUP_PREFIX, prefix=JOB_PREFIX))
print(f"wrote {len(rows)} sbatch files to sbatch/jobs/  "
      f"(prefix={JOB_PREFIX}, agent={AGENT}, group={GROUP_PREFIX})")
