"""Generate a per-family hyper sweep for the families the baseline flagged as failing.

Coordinate sweep, not cross-product: one lever changed at a time from the family's
baseline row in slurm/tasks.tsv, on representative task(s), 1 seed, 500k steps
(the repo's documented gates land by 100-250k). Levers with documented leverage:
  expectile     -- the proven dominant lever (v11.2's cap-breaker)
  adv_temp/drift_step -- the remaining v11.1->v11.2 actor-sharpness deltas
  rho           -- critic pessimism, mainly for sparse manipulation

Usage (after the baseline finishes):
    python sbatch/gen_sweep.py cube-double-play scene-play    # -> sbatch/jobs-sweep/
    JOBS_DIR=sbatch/jobs-sweep bash sbatch/submit_all.sh      # submit the sweep
Edit LEVERS below to change the grid; regenerate any time.
"""
import os, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
N_TASKS = int(os.environ.get("N_TASKS", 1))          # representative tasks per family (task1..taskN)
SWEEP_STEPS = int(os.environ.get("SWEEP_STEPS", 500000))
GROUP = os.environ.get("SWEEP_GROUP", "DQL112-ABL")
AGENT = os.environ.get("SWEEP_AGENT", "agents/dql_v11_2.py")
MAX_WINDOWS = 6

# lever -> candidate values; the family's baseline value is skipped automatically.
# Grid = the reviewer's factorial ablation (staged: coordinate sweep around the
# v11.2 recipe) + the DriftQL single-positive premise ablation (n_cand=1).
LEVERS = {
    "expectile":        [0.5, 0.9],                  # F3: propagation vs kappa
    "agent.adv_temp":   [0.125, 0.5, 1.0],           # F4: blur U-curve (0.25 = baseline)
    "agent.drift_step": [0.5, 1.0, 2.0],             # F4/F5: eta slice (1.5 = baseline)
    "agent.q_coef":     [0.0, 0.1, 0.5, 1.0],        # F5: stability slice (0.25 = baseline)
    "agent.n_cand":     [1],                         # M=1: DriftQL's single-positive premise
    "rho":              [0.0, 1.0],
}

TEMPLATE = """#!/bin/bash
#SBATCH --account=edgeai_tao-ptm_image-foundation-model-clip
#SBATCH --partition=polar4,polar3,polar,grizzly
#SBATCH --time=4:00:00
#SBATCH --nodes=1
#SBATCH --gpus-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=100G
#SBATCH --dependency=singleton
#SBATCH --job-name={job}
#SBATCH --output={repo}/logs/%x.%j.log
#SBATCH --error={repo}/logs/%x.%j.log
#SBATCH --open-mode=append
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=chrislin@nvidia.com
# sweep variant: {env}  {tag}
# GENERATED by sbatch/gen_sweep.py -- edit the grid there, not this file.

export REPO={repo}
export AGENT={agent}
export RUN_ENV={env} RUN_H={h} RUN_EXP={exp} RUN_RHO={rho} RUN_DISC={disc} RUN_SPARSE={sparse}
export RUN_EXTRA="{extra}"
export RUN_STEPS={steps} RUN_NAME={run_name} RUN_GROUP={group}/{env}
bash "$REPO/sbatch/run_sweep.sh"
rc=$?

CNT="$REPO/logs/$SLURM_JOB_NAME.windows"
n=$(($(cat "$CNT" 2>/dev/null || echo 0) + 1)); echo "$n" > "$CNT"
if [ "$rc" -eq 99 ] && [ "$n" -lt {max_windows} ]; then
    scontrol requeue "$SLURM_JOB_ID"
elif [ "$rc" -eq 99 ]; then
    echo "hit MAX_WINDOWS={max_windows}" >&2; exit 1
else
    exit "$rc"
fi
"""


def main():
    families = sys.argv[1:]
    if not families:
        sys.exit("usage: python sbatch/gen_sweep.py <family> [family ...]   e.g. cube-double-play")

    rows = {}
    with open(os.path.join(REPO, "slurm/tasks.tsv")) as f:
        next(f)
        for line in f:
            env, h, exp, rho, disc, sparse = line.rstrip("\n").split("\t")
            rows[env] = dict(h=h, exp=exp, rho=rho, disc=disc, sparse=sparse)

    outdir = os.path.join(REPO, "sbatch/jobs-sweep")
    os.makedirs(outdir, exist_ok=True)
    n = 0
    for fam in families:
        for t in range(1, N_TASKS + 1):
            env = f"{fam}-singletask-task{t}-v0"
            if env not in rows:
                sys.exit(f"unknown family/task: {env} (not in slurm/tasks.tsv)")
            base = rows[env]
            for lever, values in LEVERS.items():
                for v in values:
                    p = dict(base)
                    extra = ""
                    if lever == "expectile":
                        if float(v) == float(base["exp"]): continue
                        p["exp"] = v
                    elif lever == "rho":
                        if float(v) == float(base["rho"]): continue
                        p["rho"] = v
                    else:
                        extra = f"--{lever}={v}"
                    tag = f"{lever.replace('agent.', '')}{v}"
                    run_name = f"sweep__{env}__{tag}"
                    job = f"dqlswp-{fam}-t{t}-{tag}"
                    path = os.path.join(outdir, f"{job}.sbatch")
                    with open(path, "w") as f:
                        f.write(TEMPLATE.format(
                            repo=REPO, env=env, job=job, run_name=run_name, group=GROUP, tag=tag, agent=AGENT,
                            h=p["h"], exp=p["exp"], rho=p["rho"], disc=p["disc"], sparse=p["sparse"],
                            extra=extra, steps=SWEEP_STEPS, max_windows=MAX_WINDOWS))
                    n += 1
    print(f"wrote {n} sweep jobs to sbatch/jobs-sweep/  "
          f"({len(families)} families x {N_TASKS} task(s), {SWEEP_STEPS:,} steps, 1 seed)")
    print(f"submit: JOBS_DIR=sbatch/jobs-sweep bash sbatch/submit_all.sh")


if __name__ == "__main__":
    main()
